# Generated by Django 5.1.6 on 2025-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentData',
            fields=[
                ('dept_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"human_resources"."departments"',
                'ordering': ['dept_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"human_resources"."employees"',
                'ordering': ['employee_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('vendor_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"admin"."vendor"',
                'ordering': ['vendor_code'],
                'managed': False,
            },
        ),
    ]
