# Generated by Django 5.1.6 on 2025-04-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_get_reference_data', '0002_assetdata_materialdata_productdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetdata',
            options={'managed': False, 'ordering': ['asset_name']},
        ),
        migrations.AlterModelOptions(
            name='materialdata',
            options={'managed': False, 'ordering': ['material_name']},
        ),
        migrations.AlterModelOptions(
            name='productdata',
            options={'managed': False, 'ordering': ['product_name']},
        ),
    ]
