# Generated by Django 5.1.6 on 2025-04-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_get_reference_data', '0003_alter_assetdata_options_alter_materialdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('customer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contact_person', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"sales"."customer"',
                'ordering': ['customer_id'],
                'managed': False,
            },
        ),
    ]
