# Generated by Django 5.1.6 on 2025-05-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_get_reference_data', '0005_alter_customerdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendordata',
            table='"purchasing"."vendors"',
        ),
    ]
