# Generated by Django 5.1.6 on 2025-05-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_get_reference_data', '0006_alter_vendordata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('quotation_content_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"operations"."v_item_list_view"',
                'ordering': ['item_id'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AssetData',
        ),
        migrations.DeleteModel(
            name='MaterialData',
        ),
        migrations.DeleteModel(
            name='ProductData',
        ),
    ]
