# Generated by Django 5.1.6 on 2025-03-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReworkOrderData',
            fields=[
                ('external_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rework_id', models.CharField(max_length=255)),
                ('failed_shipment_id', models.CharField(max_length=255)),
                ('rework_status', models.CharField(max_length=255)),
                ('rework_date', models.DateField()),
            ],
            options={
                'db_table': '"operations"."v_delivery_rework_order_view"',
                'ordering': ['external_id'],
                'managed': False,
            },
        ),
    ]
