# Generated by Django 5.1.6 on 2025-03-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_delivery_receipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReceiptData',
            fields=[
                ('external_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('delivery_receipt_id', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"operations"."v_delivery_receipt_view"',
                'ordering': ['external_id'],
                'managed': False,
            },
        ),
    ]
