# Generated by Django 5.1.6 on 2025-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_delivery_receipt', '0003_billingreceiptdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalGoodsIssueData',
            fields=[
                ('external_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('goods_issue_id', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('issued_by', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': '"operations"."v_external_goods_issue_view"',
                'managed': False,
            },
        ),
    ]
