# Generated by Django 5.1.6 on 2025-04-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_delivery_receipt', '0004_externalgoodsissuedata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='externalgoodsissuedata',
            table='"operations"."external_goods_issue_summary"',
        ),
    ]
