# Generated by Django 5.1.6 on 2025-04-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_delivery_receipt', '0005_alter_externalgoodsissuedata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryreworkorderdata',
            table='"operations"."v_delivery_return_order_view"',
        ),
        migrations.AlterModelTable(
            name='externalgoodsissuedata',
            table='"operations"."v_external_goods_issue"',
        ),
    ]
