# Generated by Django 5.1.6 on 2025-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_update_delivery_approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryApprovalData',
            fields=[
                ('external_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('approval_request_id', models.CharField(max_length=255)),
                ('request_date', models.DateField()),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')])),
                ('approval_date', models.DateField()),
                ('approved_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"operations"."v_delivery_approval_view"',
                'ordering': [models.Case(models.When(approval_status='Pending', then=models.Value(1)), models.When(approval_status='Approved', then=models.Value(2)), models.When(approval_status='Rejected', then=models.Value(3)), output_field=models.IntegerField()), 'request_date'],
                'managed': False,
            },
        ),
    ]
