# Generated by Django 5.1.6 on 2025-04-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_update_delivery_approval', '0002_deliveryapprovaldata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryapprovaldata',
            table='"distribution"."logistics_approval_request"',
        ),
    ]
