# Generated by Django 5.1.6 on 2025-04-02 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTrackingData',
            fields=[
                ('document_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(unique=True)),
                ('document_no', models.IntegerField(unique=True)),
                ('status', models.TextField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Draft', 'Draft')], default='Draft')),
                ('posting_date', models.DateField(default=datetime.date.today)),
                ('transaction_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"operations"."document_header"',
                'ordering': ['document_id'],
                'managed': False,
            },
        ),
    ]
