# Generated by Django 5.1.6 on 2025-04-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('vendor_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"admin"."vendor"',
                'ordering': ['vendor_code'],
                'managed': False,
            },
        ),
    ]
