# Generated by Django 5.1.6 on 2025-04-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0003_employeedata_departmentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItems',
            fields=[
                ('content_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=255)),
                ('material_id', models.CharField(max_length=255)),
                ('product_docu_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_no', models.CharField(max_length=255)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"operations"."document_items"',
                'ordering': ['content_id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='departmentdata',
            options={'managed': False, 'ordering': ['dept_id']},
        ),
    ]
