# Generated by Django 5.1.6 on 2025-04-03 12:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0004_documentitems_alter_departmentdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"admin"."assets"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialData',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': '"admin"."raw_materials"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': '"admin"."products"',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='departmentdata',
            table='"human_resources"."departments"',
        ),
        migrations.CreateModel(
            name='ProductDocuItemData',
            fields=[
                ('productdocu_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manuf_date', models.DateField(default=datetime.date.today, editable=False)),
                ('expiry_date', models.DateField(default=datetime.date.today, editable=False)),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='feature_goods_tracking.productdata')),
            ],
        ),
    ]
