# Generated by Django 5.1.6 on 2025-04-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0005_assetdata_materialdata_productdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocuitemdata',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_products', to='feature_goods_tracking.productdata'),
        ),
    ]
