# Generated by Django 5.1.6 on 2025-04-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0006_alter_productdocuitemdata_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdocuitemdata',
            options={'managed': False},
        ),
    ]
