# Generated by Django 5.1.6 on 2025-04-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0008_productcostdata_alter_productdocuitemdata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentData',
        ),
        migrations.DeleteModel(
            name='EmployeeData',
        ),
        migrations.DeleteModel(
            name='VendorData',
        ),
    ]
