# Generated by Django 5.1.6 on 2025-04-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0011_serialtrackingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceData',
            fields=[
                ('invoice_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': '"sales"."sales_invoices"',
                'managed': False,
            },
        ),
    ]
