# Generated by Django 5.1.6 on 2025-04-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0012_salesinvoicedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstrackingdata',
            options={'managed': False, 'ordering': ['-transaction_id']},
        ),
    ]
