# Generated by Django 5.1.6 on 2025-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_goods_tracking', '0013_alter_goodstrackingdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"operations"."v_item_list_view"',
                'ordering': ['item_id'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AssetData',
        ),
        migrations.DeleteModel(
            name='MaterialData',
        ),
        migrations.DeleteModel(
            name='ProductCostData',
        ),
        migrations.RemoveField(
            model_name='productdocuitemdata',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='SerialTrackingData',
        ),
        migrations.DeleteModel(
            name='ProductData',
        ),
        migrations.DeleteModel(
            name='ProductDocuItemData',
        ),
    ]
