# Generated by Django 5.1.6 on 2025-03-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getWarehouseIDData',
            fields=[
                ('warehouse_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"admin"."warehouse"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalTransferDeliveryRequestData',
            fields=[
                ('external_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(max_length=255)),
                ('delivery_type', models.CharField(max_length=255)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('module_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"operations"."v_internal_delivery_request_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='updateDRWarehouseData',
            fields=[
                ('content_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"operations"."document_items"',
                'managed': False,
            },
        ),
    ]
