# Generated by Django 5.1.6 on 2025-04-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_internal_transfer', '0002_internaltransferreworkorderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendToDistributionData',
            fields=[
                ('del_order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"distribution"."delivery_order"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='updateDeliveryRequestData',
            fields=[
                ('content_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('delivery_request_id', models.CharField(max_length=255)),
                ('warehouse_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"operations"."document_items"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='updateDRWarehouseData',
        ),
    ]
