# Generated by Django 5.1.6 on 2025-04-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_internal_transfer', '0004_productionorderdata_externalmoduleproductorderdata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalmoduleproductorderdata',
            options={'ordering': ['production_order_detail_id']},
        ),
        migrations.AlterModelOptions(
            name='internaltransferdeliveryrequestdata',
            options={'managed': False, 'ordering': ['request_date']},
        ),
        migrations.AlterModelOptions(
            name='productionorderdata',
            options={'managed': False, 'ordering': ['actual_quantity']},
        ),
    ]
