# Generated by Django 5.1.6 on 2025-03-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_asset_removal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendToManagement',
            fields=[
                ('approval_id', models.CharField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(unique=True)),
            ],
            options={
                'db_table': '"management"."management_approvals"',
                'managed': False,
            },
        ),
    ]
