# Generated by Django 5.1.6 on 2025-04-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_asset_removal', '0002_sendtomanagement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetremovaldata',
            table='"operations"."v_item_removal_view"',
        ),
    ]
