# Generated by Django 5.1.6 on 2025-04-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_asset_removal', '0003_alter_assetremovaldata_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetremovaldata',
            options={'managed': False, 'ordering': ['reported_date']},
        ),
    ]
