# Generated by Django 5.1.6 on 2025-04-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_get_purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasequotationdata',
            table='"purchasing"."purchase_quotation"',
        ),
        migrations.AlterModelTable(
            name='purchaserequestdata',
            table='"purchasing"."purchase_requests"',
        ),
        migrations.AlterModelTable(
            name='quotationcontentsdata',
            table='"purchasing"."quotation_contents"',
        ),
    ]
