# Generated by Django 5.1.6 on 2025-04-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_get_purchase_order', '0002_alter_purchasequotationdata_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderData',
            fields=[
                ('purchase_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document_date', models.DateField()),
            ],
            options={
                'db_table': '"purchasing"."purchase_order"',
                'ordering': ['purchase_id'],
                'managed': False,
            },
        ),
    ]
